import { AddressDTO } from "./address.dto";

export interface TripTicketExportData {
  // Core trip data
  id?: string;
  ticket_id?: string;
  origin_provider_id?: number;
  origin_customer_id?: string;
  customer_last_name?: string;
  customer_first_name?: string;
  customer_middle_name?: string;
  customer_middle_initial?: string;
  customer_mi?: string;
  customer_dob?: string;
  customer_gender?: string;
  customer_race?: string;
  primary_language?: string;
  customer_email?: string;
  customer_ethnicity?: string;
  customer_nick_name?: string;
  customer_poverty_level?: string;
  customer_disability?: string;
  customer_veteran?: string;
  customer_internal_id?: string;
  requested_pickup_date?: string;
  _requested_pickup_date?: string;
  requested_dropoff_date?: string;
  _requested_dropff_date?: string;
  requested_pickup_time?: string;
  _requested_pickup_time?: string;
  requested_dropOff_time?: string;
  requested_dropoff_time?: string;
  _requested_dropoff_time?: string;
  requester_trip_id?: string;
  customer_mobility_factors?: string;
  common_trip_id?: string;
  approved_trip_claim_id?: number;

  trip_result?: {
    driverId?: string;
    driverName?: string;
    vehicleId?: string;
    vehicleName?: string;
    actualPickupArriveTime?: string;
    actualDropOffArriveTime?: string;
    actualPickupDepartTime?: string;
    actualDropOffDepartTime?: string;
    no_show_reason?: string;
    cancellation_reason?: string;
    fare?: string;
    fareCollected?: string;
  };

  // Address data
  pickup_address?: AddressDTO;
  drop_off_address?: AddressDTO;
  customer_address?: AddressDTO;

  status?: {
    type: string;
    id:number;
  };

  // Additional fields
  pickup_note?: string;
  PU_NOTE?: string;
  trip_notes?: string;
  customer_home_phone?: string;
  customer_emergency_phone?: string;
  customer_emergency_contact_name?: string;
  customer_emergency_contact_phone?: string;
  customer_emergency_contact_relationship?: string;
  customer_mobile_phone?: string;
  customer_mailing_billing_address?: string;
  customer_caregiver_name?: string;
  customer_caregiver_contact_info?: string;
  customer_care_info?: string;
  customer_funding_billing_information?: string;
  impairment_description?: string;
  customer_information_withheld?: boolean;
  customer_notes?: string;
  boarding_time?: number;
  deboarding_time?: number;
  pu_phone?: string;
  dropoff_note?: string;
  DO_NOTE?: string;
  originator?: { providerName?: string };
  providerName?: string;
  funding_source?: string;
  fundingSource?: string;
  funding_type?: string;
  sponsor?: string;
  purpose?: string;
  tripPurpose?: string;
  trip_purpose?: string;
  fare_type?: string;
  fareType?: string;
  fare?: string;
  num_attendant?: string;
  attendants?: number;
  guests?: number;
  customer_seats_required?: string;
  device?: string;
  vehicle_required?: string;
  vehicle_type?: string;
  VEHICLE_REQ?: string;
  scheduling_priority?: string;
  customer_identifiers?: string;
  customer_eligibility_factors?: string;
  customer_service_animals?: boolean;
  trip_funders?: string;
  tripFundersList?: string[];
  customer_assistance_needs?: string;
  attendant_mobility_factors?: string;
  guest_mobility_factors?: string;
  service_level?: string;
  earliest_pickup_time?: string;
  appointment_time?: string;
  customerLoadTime?: string;
  customerUnloadTime?: string;
  estimated_trip_travel_time?: number;
  estimated_trip_distance?: number;
  is_trip_isolation?: boolean;
  is_outside_coreHours?: boolean;
  time_window_before?: number;
  time_window_after?: number;
  provider_white_list?: string;
  provider_black_list?: string;
  last_status_changed_by_providerId?: number;
  trip_ticket_provisional_time?: string;
  provisional_provider_id?: number;
  expiration_date?: string;
  is_expired?: boolean;
  customer_custom_fields?: string;
  trip_custom_fields?: string;
  version?: string;
  customerStatusForDuplication?: string;
  isEligibleForClaim?: boolean;
  isTripCancel?: boolean;
  isTripTicketInvisible?: boolean;
  created_at?: string;
  updated_at?: string;
}
