import { firebaseConfig } from './firebase.config';

export const environment = {
  production: true,
  apiUrl: 'https://tripexchange.demandtrans-apis.com/api/',
  apiTimeout: 60000,
  version: '1.0.0',
  logLevel: 'error', // Only log errors in production
  enableDebugTools: false,
  mockApiCalls: false,

  /**
   * Firebase Identity Platform reCAPTCHA v3 Site Key
   *
   * This key is auto-generated by Firebase Identity Platform and is required for:
   * - Multi-Factor Authentication (MFA) enrollment
   * - Firebase App Check validation
   *
   * Key: 6LeU-M0rAAAAADixTIDh_W_USDqyqVhzHIIJ_nbS
   * Type: Trip Exchange Production (Web)
   * Configuration: allowedDomains = exchange.demandtrans-apis.com
   *
   * ⚠️ Updated to use the production-specific key for proper domain validation
   *
   * Note: This replaces the previous Identity Platform key (6LexLc0rAAAAANn2ZO7nbF3834OTPiROoxodd8gj)
   * which had allowAllDomains but was causing 403 errors in production.
   */
  appCheckRecaptchaSiteKey: '6LeU-M0rAAAAADixTIDh_W_USDqyqVhzHIIJ_nbS',

  firebase: firebaseConfig,
  // Production redirect URL for password reset action (updated to match actual domain)
  passwordResetRedirectUrl: 'https://exchange.demandtrans-apis.com/reset-password',
  // Base64-encoded shared AES key used to encrypt email for login/validateUser.
  // In production this should be set to the same key used by the backend's SharedEncryptionService.
  loginValidateSharedKey: 'SXQ3Ts2EWvmWTWYWDW0VGXg2gokvo6STgy75Riv251c=',
};
